# Generated by Django 3.1.2 on 2020-10-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sightings1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_Squirrel_ID', models.CharField(max_length=14)),
                ('Date', models.DateField()),
            ],
        ),
    ]
