# Generated by Django 3.1.2 on 2020-10-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('Latitude', models.FloatField(help_text='X Latitude')),
                ('Longitude', models.FloatField(help_text='Y longitude')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=14, primary_key=True, serialize=False)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='PM', help_text='Shift choice', max_length=2)),
                ('Date', models.DateField(help_text='Date of record')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of Squirrel', max_length=10)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Color of Squirrel', max_length=10)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=20)),
                ('Specific_Location', models.TextField(blank=True)),
                ('Running', models.BooleanField(default=False, help_text='whether the squirrel is running or not')),
                ('Chasing', models.BooleanField(default=False, help_text='whether the squirrel is chasing or not')),
                ('Climbing', models.BooleanField(default=False, help_text='whether the squirrel is climbing or not')),
                ('Eating', models.BooleanField(default=False, help_text='whether the squirrel is eating or not')),
                ('Foraging', models.BooleanField(default=False, help_text='whether the squirrel is foraging or not')),
                ('Other_Activity', models.TextField(blank=True)),
                ('Kuks', models.BooleanField(default=False, help_text='whether the squirrel has kuks or not')),
                ('Quaas', models.BooleanField(default=False, help_text='whether the squirrel has quaas or not')),
                ('Moans', models.BooleanField(default=False, help_text='whether the squirrel has moans or not')),
                ('Tail_Flags', models.BooleanField(default=False, help_text='whether the squirrel has tail falgs or not')),
                ('Tail_Twitches', models.BooleanField(default=False, help_text='whether the squirrel has tail twitches or not')),
                ('Approaches', models.BooleanField(default=False, help_text='whether the squirrel has approaches or not')),
                ('Indifferent', models.BooleanField(default=False, help_text='whether the squirrel is indifferent or not')),
                ('Runs_From', models.BooleanField(default=False, help_text='whether the squirrel runs from or not')),
            ],
        ),
        migrations.DeleteModel(
            name='Sightings1',
        ),
    ]
