# Generated by Django 3.1.2 on 2020-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_auto_20201019_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of Squirrel', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Color of Squirrel', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=100, primary_key=True, serialize=False),
        ),
    ]
