# Generated by Django 3.1.2 on 2020-10-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20201019_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Approaches',
            field=models.BooleanField(help_text='whether the squirrel has approaches or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Chasing',
            field=models.BooleanField(help_text='whether the squirrel is chasing or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Climbing',
            field=models.BooleanField(help_text='whether the squirrel is climbing or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Eating',
            field=models.BooleanField(help_text='whether the squirrel is eating or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foraging',
            field=models.BooleanField(help_text='whether the squirrel is foraging or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Indifferent',
            field=models.BooleanField(help_text='whether the squirrel is indifferent or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Kuks',
            field=models.BooleanField(help_text='whether the squirrel has kuks or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Moans',
            field=models.BooleanField(help_text='whether the squirrel has moans or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Quaas',
            field=models.BooleanField(help_text='whether the squirrel has quaas or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Running',
            field=models.BooleanField(help_text='whether the squirrel is running or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Runs_From',
            field=models.BooleanField(help_text='whether the squirrel runs from or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Tail_Flags',
            field=models.BooleanField(help_text='whether the squirrel has tail falgs or not'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Tail_Twitches',
            field=models.BooleanField(help_text='whether the squirrel has tail twitches or not'),
        ),
    ]
