# Generated by Django 3.1.2 on 2020-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_auto_20201019_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Shift choice', max_length=2),
        ),
    ]
