# Generated by Django 3.1.2 on 2020-10-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_auto_20201019_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
