# Generated by Django 3.1.2 on 2020-10-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20201022_2134'),
        ('squirrel', '0006_auto_20201022_2024'),
    ]

    operations = [
    ]
