# Generated by Django 3.1.2 on 2020-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0007_merge_20201022_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=40, primary_key=True, serialize=False),
        ),
    ]
